version: '3.7'
services:
  project:
    container_name: project
    build: ../project
    volumes:
      - '../project:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start